### ISSUE TITLE
An Error  reported when check the help information of this library 

### ISSUE THREAD

**Issue by WinterLi1993** [sbg/sevenbridges-python#107] opened 2018-11-20 07:58 UTC
Hi, 
import sevenbridges as sbg 
help(sbg)
when I  execute this command "help(sbg") ,the error prompt reported as the following information .
so what happened ?

/data2/bin/lib/python3.6/site-packages/sevenbridges/meta/resource.py in __get__(cls, obj, objtype)
     82     def __get__(cls, obj, objtype=None):
     83         # SPHINX_DOC part is for generating documentation
---> 84         if not isinstance(obj, HttpClient) and not os.environ['SPHINX_DOC']:
     85             raise SbgError(message='Improperly configured client!')
     86         if obj is None:

/data2/bin/lib/python3.6/os.py in __getitem__(self, key)
    667         except KeyError:
    668             # raise KeyError with the original key value
--> 669             raise KeyError(key) from None
    670         return self.decodevalue(value)
    671 

KeyError: 'SPHINX_DOC'

**Comment by WinterLi1993** [comment] 2018-11-21 08:43
@msrdic  please check this upper  question ,thanks

**Comment by QuicksilverMachine** [comment] 2018-11-21 09:45
Hey @WinterLi1993, I checked and this was caused by a validation to see if the client is properly configured. It will be fixed in the next release.

**Comment by QuicksilverMachine** [comment] 2018-11-22 10:55
This is fixed in release version [0.17.1](https://github.com/sbg/sevenbridges-python/releases/tag/0.17.1)

**Closed by QuicksilverMachine** 2018-11-22 10:55 UTC
