### ISSUE TITLE
reload method on volumes import returns None

### ISSUE THREAD

**Issue by sethi7ik** [sbg/sevenbridges-python#40] opened 2016-09-27 22:03 UTC
imp = api.imports.submit_import(volume=volume_import, project=my_project, location=bucket_location)
time.sleep(30)
#Wait until the import finishes
while True:
      import_status = imp.reload().state

 imp.reload() was returning None which lead to error
this is inspite of the import actually taking place
what worked for me was: 
imp = api.imports.submit_import(volume=svolume_im, project=smy_project, location=sfilename)
#Wait until the import finishes    
import_status = ''
time.sleep(30)
i = api.imports.get(id=imp.id)
print i.state

**Comment by SenadI** [comment] 2016-09-27 22:05
@sethi7ik Will be investigated promptly. If the issue is confirmed expect the resolution and a minor version update very soon.

Thank you for catching this one!

**Comment by sethi7ik** [comment] 2016-09-27 22:07
Thanks @SenadI

**Comment by SenadI** [comment] 2016-09-29 08:30
@sethi7ik Fixed in v0.5.3 version.

**Closed by SenadI** 2016-09-29 08:30 UTC
